# GitLab CI Pipeline Configuration
stages:
  - build

build-aarch64:
  stage: build
  image: konstin2/maturin  # Docker image with maturin preinstalled
  variables:
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc  # Ensure the correct linker is used
    CARGO_BUILD_TARGET: aarch64-unknown-linux-gnu  # Set the target architecture
    PYO3_CROSS: "1"  # Enable PyO3 cross-compilation

  before_script:
    # Install dependencies for cross-compilation
    - apt-get update && apt-get install -y gcc-aarch64-linux-gnu python3 python3-dev
    # Ensure Python cross-compilation support
    - rustup target add aarch64-unknown-linux-gnu

  script:
    # Build the Python package for aarch64
    - pip install uv && uv pip install twine
    - maturin build --release --target aarch64-unknown-linux-gnu
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
