# GitLab CI Pipeline Configuration
stages:
  - build
  - test

build-aarch64:
  stage: build
  image:
    name: registry.gitlab.rylanswebsite.com/rylan-meilutis/rust-docker-builder:arm64  # Docker image with maturin preinstalled
    docker:
      platform: linux/arm64/v8
  id_tokens:
    PYPI_ID_TOKEN:
      # Use "testpypi" if uploading to TestPyPI
      aud: pypi
  variables:
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc  # Ensure the correct linker is used
    CARGO_BUILD_TARGET: aarch64-unknown-linux-gnu  # Set the target architecture

  script:
    - rustup target add aarch64-unknown-linux-gnu
    - python3.11 -m venv venv && source venv/bin/activate
    - pip3 install uv && uv pip install maturin twine
    # Build the Python package for aarch64
    - maturin build --release --target aarch64-unknown-linux-gnu
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi target/wheels/*
    - api_token=$PYPI_TOKEN
    - twine upload -u __token__ -p "${api_token}" target/wheels/*

  only:
    - pushes
    - main

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml


